Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 1000

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false
